Add support for Gemfile and enable molecule tests
ome/ansible-role-jekyll-build pull request #1
Opened 2017-05-12 13:33 UTC by sbesson

Following issues reported in https://github.com/IDR/idr.openmicroscopy.org/pull/22, this PR:

- configures `molecule` to test this role
- adds support for top-level `Gemfile` in the tasks
- attempts to fix the deployment issue by removing curly braces in conditional

I have not been able to reproduce the last problem via the idempotence tests.  However, the double braces in conditionals are flagged by the Ansible and have been flagged as source of errors (https://github.com/ansible/ansible/issues/13270).

If it makes review easier, happy to separate the `Gemfile` addition from the molecule tests enabling.

2017-05-12 16:16 UTC, sbesson commented
With the last commit

```
[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/travis/build/openmicroscopy/ansible-role-jekyll-build/tasks/main.yml:61
Task/Handler: jekyll | update bundle
[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/travis/build/openmicroscopy/ansible-role-jekyll-build/tasks/main.yml:72
Task/Handler: jekyll | build jekyll website
```

is kind of unfortunate for the progress on this front and nicely flagging pieces where refactoring is due at the same time. I might look into the migration of the `bundle install` and `jekyll build` steps as role handlers assuming no-one has an better idea or immediate need for this work. /cc @joshmoore

2017-05-15 06:39 UTC, joshmoore commented on .travis.yml
> +- pip install ansible docker 'molecule<1.22'
`ome-ansible-molecule-dependencies`?

2017-05-22 11:08 UTC, manics commented on molecule.yml
> +    privileged: True
Does the plain centos image work?
```
- name: ansible-role-basedeps
  image: centos
  image_version: 7
```

2017-05-22 17:49 UTC, sbesson commented on molecule.yml
> +    privileged: True
Yes, thanks for spotting the copy-and-paste of another roles (depending on `systemd` most likely) - pushed as 204ba1b.

2017-06-08 13:19 UTC, sbesson commented
@manics what do you think of the status/todos on this PR? If that seems like an overall improvement, we could get this merged, tagged and deployed `1.1.0`. Then the IDR playbooks could try to upgrade to this version to see if it solves some of the issues with updating existing deployment. /cc @joshmoore

2017-06-09 18:05 UTC, manics commented
Looks generally fine, though I haven't had a chance to test updates of existing repos yet.

One issue for others to consider (pre-existing issue so not a blocker): The default owner is `root` which means the default location is [`/home/root`](https://github.com/openmicroscopy/ansible-role-jekyll-build/blob/master/defaults/main.yml#L7). Would [`/srv`](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure) be better?

2017-06-09 18:05 UTC, manics requested changes

2017-06-09 18:05 UTC, manics commented on molecule.yml
> +    jekyll-build:
Could you move this var into the playbook for clarity? host-vars are useful when you're testing multiple hosts with different configs, but in this case there's only one.

2017-06-09 18:05 UTC, manics commented on tests/test_default.yml
> +import testinfra.utils.ansible_runner
This file should be called `test_default.py`

2017-06-09 18:05 UTC, manics commented on tests/test_default.yml
> +def test_hosts_file(File):
Could you change this to test for the existence of a file generated by jekyll, such as `/var/www/localhost/html/index.html`. Optionally grep for the existence of a templated string that should be substituted in the file after generation. Example test syntax: https://github.com/openmicroscopy/ansible-role-postgresql/blob/2.0.0/tests/test_postgresql_94.py#L23

2017-06-12 08:06 UTC, sbesson commented
Pushed all changes to the test as suggested in https://github.com/openmicroscopy/ansible-role-jekyll-build/pull/1#pullrequestreview-43220449. Re default location, probably worth revisiting in a follow-up PR.

2017-06-12 08:38 UTC, manics commented
LGTM

2017-06-12 09:52 UTC, joshmoore commented
Targeted tag? 2.0.0?

2017-06-12 10:27 UTC, manics commented
Depends whether you want the location to be changed or not.

2017-06-12 10:30 UTC, sbesson commented
As mentioned in https://github.com/openmicroscopy/ansible-role-jekyll-build/pull/1#issuecomment-307100746, I would be fine with a `1.1.0`. My expectation is that this PR is adding features in a backwards-compatible manner

2017-06-12 10:33 UTC, joshmoore commented
@manics?

2017-06-12 11:14 UTC, manics commented
Sounds fine to me.

2017-06-12 11:16 UTC, merged